### ISSUE TITLE
CMIS ERROR

### ISSUE THREAD

**Issue by smangukiya** [OCA/connector-cmis#23]
Hello,

I have installed cmis, cmis_fied, cmis_web modules to odoo v10.0 enterprise. When I switch to Document Tab of any partner I got "type" error as attached.

Any one help me with this issue please? 

Thanks in advanced.
![cmis_error](https://user-images.githubusercontent.com/13784881/29677564-207450da-8919-11e7-9b18-3a1f5da47b02.jpg)

**Comment by sumankhk** [comment]
I have been facing a similar issue for a long time now.

**Comment by smangukiya** [comment]
@sumankhk : Well, I got a solution in other way around like if we do following:

1. Turn off, nginx server
2. Run Odoo server in browser with HTTP protocol (not with HTTPS)
3. Hit browser with IP ADDRESS:PORT NO (for ex: http://127.0.0.0:8069)

By doing this, I was able to see CMIS connector features.

I hope this will help you as well.

**Comment by lmignon** [comment]
@smangukiya  @sumankhk To make a good diagnosis, it is necessary to have more information. This type of error is quite generic and can be caused by various problems preventing the connection to Alfresco from your browser. In such cases, the information provided in your browser's console allows you to determine what the real problem is. If I'm not wrong for @smangukiya the problem seems to be related to the nginx configuration and the error displayed into the console was 'ERR_INCOMPLETE_CHUNKED_ENCODING'
